server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true                  # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true            # 쿼리 보기 좋게 포맷팅

    jwt:
        expiration: 1
        secretKey: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==
        secretKeyRt: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==
        expirationRt: 2

logging:
  level:
    org.hibernate.SQL: debug                  # 쿼리 로그 출력
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 쿼리 파라미터 출력
